sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t tastee/tastee:$TRAVIS_TAG --build-arg CACHEBUST=$(date +%s) .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push tastee/tastee:$TRAVIS_TAG
